import './reset.scss'
import './style.scss'
import './pages/ui-kit/colors&type/colors&type.scss'
import './img/main-icon.svg'
import './pages/ui-kit/formElements/dropdown/dropdown.js'
import './plugins/jquery-mask/jquery.mask.js'
import './pages/ui-kit/formElements/masked-text-field/masked-text-field.js'
import './pages/ui-kit/formElements/date-dropdown/date-dropdown.js'
