import './style.scss';
import './img/main-icon.svg';
import './img/murad.png';
import './pages/ui-kit/formElements/formElements';
import './pages/ui-kit/formElements/dropdown/dropdown';
import './pages/ui-kit/formElements/text-field/text-field';
import './pages/ui-kit/formElements/date-dropdown/date-dropdown';
import './pages/ui-kit/formElements/subscription-text-field/subscription-text-field';
// import './pages/ui-kit/formElements/expandable-checkbox/expandable-checkbox';
// import './pages/ui-kit/formElements/checkbox-buttons/checkbox-buttons';
// import './pages/ui-kit/formElements/radio-buttons/radio-buttons';
// import './pages/ui-kit/formElements/toggle/toggle';
// import './pages/ui-kit/formElements/like-button/like-button';
// import './pages/ui-kit/formElements/rate-button/rate-button';
// import './pages/ui-kit/formElements/rich-checkbox-buttons/rich-checkbox-buttons';
// import './pages/ui-kit/formElements/range-slider/range-slider';
// import './pages/ui-kit/formElements/pagination/pagination';
